# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 958b928d2e3583638751a99b9fcd0fc692f6df04fb20e263711c98930998844be39b96448ef2e731986e310c43bf88e40a89c9b4c28aa30ececf591df9185af6

test:
  secret_key_base: b4f8e0e8bb030d498dfde9778e526646cfaff46b5a97b6db72b92cf373227e004da201395f6170017d5da6afdc34347fd1276c60059467eb0897af68d056bbf6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
